server:
  port: 8989
  context-path: /test
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/empl
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  type-aliases-package: com.baizhi.entity
